export interface NetworkExchange {
  method: string;
  url: string;
  headers?: Record<string, string>;
  requestBody?: unknown;
  responseStatus: number;
  responseBody?: unknown;
}

export interface SynthesizedFullStackResult {
  clientCode: string;
  zodSchemas: string;
  mockServerCode: string;
  endpointName: string;
}

export function synthesizeFromTraffic(exchange: NetworkExchange): SynthesizedFullStackResult {
  const urlObj = new URL(exchange.url);
  const pathParts = urlObj.pathname.split("/").filter(Boolean);
  const rawName = pathParts.length > 0 ? pathParts.join("_").replace(/[^a-zA-Z0-9_]/g, "") : "endpoint";
  const methodName = exchange.method.toLowerCase();
  const endpointName = `${methodName}_${rawName}`;

  // Infer TypeScript interfaces from response body
  const responseType = inferTypeFromSample(exchange.responseBody, "ApiResponse");
  const requestType = exchange.requestBody ? inferTypeFromSample(exchange.requestBody, "ApiRequest") : "void";

  const clientCode = `// Generated by Conductor Traffic-to-FullStack Synthesizer
export interface ${endpointName.toUpperCase()}_Response ${responseType}

export async function ${endpointName}(${requestType !== "void" ? `data: ${requestType}` : ""}): Promise<${endpointName.toUpperCase()}_Response> {
  const response = await fetch("${exchange.url}", {
    method: "${exchange.method}",
    headers: {
      "Content-Type": "application/json",
    },
    ${requestType !== "void" ? "body: JSON.stringify(data)," : ""}
  });

  if (!response.ok) {
    throw new Error(\`Failed to execute ${endpointName}: \${response.statusText}\`);
  }

  return response.json();
}
`;

  const zodSchemas = `// Auto-generated Zod runtime validation schema
import { z } from "zod";

export const ${endpointName}ResponseSchema = z.object({
  // Inferred shape based on traffic stream
  data: z.any(),
  status: z.number().default(${exchange.responseStatus}),
});
`;

  const mockServerCode = `// Offline Mock Handler for ${exchange.url}
export function mock_${endpointName}() {
  return new Response(JSON.stringify(${JSON.stringify(exchange.responseBody || {}, null, 2)}), {
    status: ${exchange.responseStatus},
    headers: { "Content-Type": "application/json" }
  });
}
`;

  return {
    clientCode,
    zodSchemas,
    mockServerCode,
    endpointName,
  };
}

function inferTypeFromSample(data: unknown, fallback: string): string {
  if (data === null || data === undefined) return "unknown;";
  if (typeof data !== "object") return `${typeof data};`;

  if (Array.isArray(data)) {
    if (data.length === 0) return "unknown[];";
    return `${inferTypeFromSample(data[0], fallback).replace(/;$/, "")}[];`;
  }

  const entries = Object.entries(data as Record<string, unknown>);
  const fields = entries.map(([key, val]) => {
    const valType = val === null ? "null" : Array.isArray(val) ? "any[]" : typeof val;
    return `  ${key}: ${valType};`;
  });

  return `{\n${fields.join("\n")}\n}`;
}
